language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: false

notifications:
  on_success:
    - change
  on_failure:
    - change

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - ./gradlew assemble
  - ./gradlew check

script:
  - ./gradlew build
