language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: false

notifications:
  on_success:
    - change
  on_failure:
    - change

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - gradle build
