language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: false

notifications:
  on_success:
    - change
  on_failure:
    - change

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - chmod +x gradlew

 script:
  - ./gradlew build
